### ISSUE TITLE
Add support for ED25519 Keys

### ISSUE THREAD

**Issue by fabianfrz** [hirura/hrr_rb_ssh#1]
It would be good, if it would support ED25519 keys, because they are more efficient than RSA.
ED25519 implementations do exist for ruby, so it should be possible (net/ssh supports it as far as I know via an optional dependency).

**Comment by hirura** [comment]
ssh-ed25519 public key algorithm is now implemented.
Please try [hrr_rb_ssh v0.2.2](https://rubygems.org/gems/hrr_rb_ssh/versions/0.2.2).

**Comment by fabianfrz** [comment]
seems to be working :+1:

**Comment by fabianfrz** [comment]
tested from master btw

**Comment by hirura** [comment]
Thanks for the prompt confirmation!
That's must be okay because the current master and gem v0.2.2 are totally same.
