### ISSUE TITLE
SFTP Server

### ISSUE THREAD

**Issue by pablomdiaz** [hirura/hrr_rb_ssh#30]
Hi hirura, thanks for the great work on this gem. I see that you introduced the concept of a request handler. How difficult do you think it would be to create a handler that implements a SFTP server?

**Comment by hirura** [comment]
If you don't mind using OpenSSH's SFTP server implementation, it is easy.

SFTP is working as a subsystem, so the handler is as follows. The sftp-server path is my macOS case. In case of Linux box, the path could be /usr/lib/openssh/sftp-server (see /etc/ssh/sshd_config's sftp subsystem).

```ruby
sftp_server_path = "/usr/libexec/sftp-server"

options['connection_channel_request_subsystem'] = HrrRbSsh::Connection::RequestHandler.new { |context|
  context.chain_proc { |chain|
    case context.subsystem_name
    when 'sftp'
      # Here, switch user, drop privileges, and/or change directory
      # Then start sftp-server with redirecting IOs
      pid = spawn(sftp_server_path, {in: context.io[0], out: context.io[1], err: context.io[2]})
      exitstatus = Process.waitpid(pid).to_i
    else
      exitstatus = 1
    end
  }
}
```

If you'd like to implement SFTP server in Ruby, it would be tough. SFTP protocol is documented [here](https://tools.ietf.org/html/draft-ietf-secsh-filexfer-13).

**Comment by pablomdiaz** [comment]
Thanks for your prompt answer. I will see if using an existing sftp subsystem can work for me.

**Comment by hirura** [comment]
Did the OpenSSH's SFTP server work for you ?

BTW, I've tried writing SFTP server code. Please refer to [hrr_rb_sftp](https://github.com/hirura/hrr_rb_sftp) as well.

**Comment by pablomdiaz** [comment]
Hi, very nice.

We decided to go with a cloud file store, and couldn't use the sftp subsystem.

**Comment by hirura** [comment]
Okay, then let me close this issue.
